# Generated by Django 3.2.6 on 2022-03-30 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=500)),
                ('cui_description', models.CharField(default=None, max_length=500)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='controls',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='controls',
            name='family',
            field=models.CharField(choices=[('access_control', 'Access Control (AC)'), ('identification_and_authentication', 'Identification and Authentication (IDA)'), ('media_protection', 'Media Protection (MP)'), ('physical_protection', 'Physical Protection (PP)'), ('system_and_communications_protection', 'System and Communications Protection (SCP)'), ('system_and_information_integrity', 'System and Information Integrity (SII)'), ('awareness_and_training', 'Awareness and Training (AT)'), ('audit_and_accountability', 'Audit and Accountability (AA)'), ('secureity_assessment', 'Security Assessment (SAS)'), ('configuration_management', 'Configuration Management (CM)'), ('incident_response', 'Incident Response (IA)'), ('maintenance', 'Maintenance (MA)'), ('personnel_security', 'Personnel Security (PS)'), ('recovery', 'Recovery (RE)'), ('risk_management', 'Risk Management (RM)'), ('asset_management', 'Asset Management (AM)')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='controls',
            name='notes',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='controls',
            name='status',
            field=models.CharField(choices=[('non-compliant', 'Non-Compliant'), ('compliant', 'Compliant'), ('non-applicable', 'Non-Applicable')], default='Non-Compliant', max_length=25),
        ),
        migrations.AlterField(
            model_name='controls',
            name='control_id',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='controls',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2', max_length=3),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(default=None, max_length=30)),
                ('email', models.CharField(default=None, max_length=50)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.organization')),
            ],
        ),
        migrations.AddField(
            model_name='controls',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.organization'),
        ),
    ]
