# Generated by Django 3.2.6 on 2022-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220405_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='family',
            field=models.CharField(choices=[('Access Control (AC)', 'Access Control (AC)'), ('Identification and Authentication (IDA)', 'Identification and Authentication (IDA)'), ('Media Protection (MP)', 'Media Protection (MP)'), ('Physical Protection (PP)', 'Physical Protection (PP)'), ('System and Communications Protection (SCP)', 'System and Communications Protection (SCP)'), ('System and Information Integrity (SII)', 'System and Information Integrity (SII)'), ('Awareness and Training (AT)', 'Awareness and Training (AT)'), ('Audit and Accountability (AA)', 'Audit and Accountability (AA)'), ('Security Assessment (SAS)', 'Security Assessment (SAS)'), ('Configuration Management (CM)', 'Configuration Management (CM)'), ('Incident Response (IA)', 'Incident Response (IA)'), ('Maintenance (MA)', 'Maintenance (MA)'), ('Personnel Security (PS)', 'Personnel Security (PS)'), ('Recovery (RE)', 'Recovery (RE)'), ('Risk Management (RM)', 'Risk Management (RM)'), ('Asset Management (AM)', 'Asset Management (AM)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='control',
            name='status',
            field=models.CharField(choices=[('Non-Compliant', 'Non-Compliant'), ('Compliant', 'Compliant'), ('Non-Applicable', 'Non-Applicable')], default='Non-Compliant', max_length=25),
        ),
    ]
