# Generated by Django 3.2.6 on 2022-04-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20220407_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=500)),
                ('role', models.CharField(default=None, max_length=50, null=True)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='control',
            name='family',
            field=models.CharField(choices=[('Access Control (AC)', 'Access Control (AC)'), ('Identification and Authentication (IDA)', 'Identification and Authentication (IDA)'), ('Media Protection (MP)', 'Media Protection (MP)'), ('Physical Protection (PP)', 'Physical Protection (PP)'), ('System and Communications Protection (SCP)', 'System and Communications Protection (SCP)'), ('System and Information Integrity (SII)', 'System and Information Integrity (SII)'), ('Awareness and Training (AT)', 'Awareness and Training (AT)'), ('Audit and Accountability (AA)', 'Audit and Accountability (AA)'), ('Security Assessment (SAS)', 'Security Assessment (SAS)'), ('Configuration Management (CM)', 'Configuration Management (CM)'), ('Incident Response (IA)', 'Incident Response (IA)'), ('Maintenance (MA)', 'Maintenance (MA)'), ('Personnel Security (PS)', 'Personnel Security (PS)'), ('Recovery (RE)', 'Recovery (RE)'), ('Risk Management (RM)', 'Risk Management (RM)'), ('Asset Management (AM)', 'Asset Management (AM)'), ('Situational Awareness (SA)', 'Situational Awareness (SA)')], default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
